language: go

go:
  - "1.10"

install:
  - go get -u github.com/kardianos/govendor
  - govendor sync

script:
  - govendor test +local -v -covermode=count -coverprofile=coverage.out
  - govendor install +local

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
